### ISSUE TITLE
Automated macOS configuration

### ISSUE THREAD

**Issue by arzg** [uggedal/cfg#1]
Hi, I noticed that you have your macOS configuration as a list of manual steps to follow. I found out a while ago, however, that it is possible to automate a lot of macOS configuration with _this one easy trick:_

```bash
$ defaults read > before
# Make the change manually
$ defaults read > before
$ vimdiff before after
```

Scroll through and find the most likely candidate for what you just changed. Remember the key (word before equals sign). Find the parent of the key to find the domain of that setting (this is displayed as being in quotes but actually isn’t), and then run something like this:

```bash
$ defaults write <domain> <key> <this can be -int, -float, -bool, or -string> <value>
```

Note that `defaults read` outputs booleans as a `0` or a `1`, but that the `defaults write` command interprets booleans as `true` or `false`.

Origin: https://pawelgrzybek.com/change-macos-user-preferences-via-command-line/

**Comment by uggedal** [comment]
Thanks for the tip! I will keep it mind for the future. I’m mostly using Linux now though.

**Comment by arzg** [comment]
Ah, ok. Should I close this issue?
